---
  - name: Configure Elk
    hosts: Elk
    become: true
    tasks:
    - name: Update cache
      apt:
       update_cache: yes
    - name: Install docker.io
      apt:
       name: docker.io

    - name: Install python3-pip
      apt:
       name: python3-pip

    - name: Install docker using pip
      pip:
       name: docker 
